// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Note is a single markdown note. DeletedAt is a unix timestamp (seconds)
 * while the note sits in the trash, and null while the note is live.
 */
export class Note {
    /**
     * Creates a new Note instance.
     * @param {Partial<Note>} [$$source = {}] - The source object to create the Note.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (!("deletedAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["deletedAt"] = null;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Note}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Note(/** @type {Partial<Note>} */($$parsedSource));
    }
}

/**
 * appHandle is the seam between services and the running Wails application.
 * It lets services emit events without importing a circular dependency on the
 * concrete app instance created in main.
 */
export class appHandle {
    /**
     * Creates a new appHandle instance.
     * @param {Partial<appHandle>} [$$source = {}] - The source object to create the appHandle.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new appHandle instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {appHandle}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new appHandle(/** @type {Partial<appHandle>} */($$parsedSource));
    }
}
