// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Note is a single markdown note. DeletedAt is a unix timestamp (seconds)
 * while the note sits in the trash, and null while the note is live.
 */
export interface Note {
    "id": string;
    "title": string;
    "content": string;
    "pinned": boolean;
    "deletedAt": number | null;
    "createdAt": number;
    "updatedAt": number;
}

/**
 * appHandle is the seam between services and the running Wails application.
 * It lets services emit events without importing a circular dependency on the
 * concrete app instance created in main.
 */
export interface appHandle {
}
