// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteService exposes note persistence to the frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateNote inserts a new note with the given markdown content and returns
 * it.
 */
export function CreateNote(content: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(3901296041, content);
}

/**
 * DeleteNoteForever removes a note from the database permanently. Only notes
 * already in the trash can be deleted forever.
 * 
 * FROZEN (pin-only form factor): same as RestoreNote — no trash UI exists.
 */
export function DeleteNoteForever(id: string): $CancellablePromise<void> {
    return $Call.ByID(4200988185, id);
}

/**
 * DiscardIfEmpty hard-deletes a note whose current content is blank. This is
 * the pin-only form factor's empty-note rule: closing a window (or the exit
 * path) flushes the editor first, then calls this — a never-typed note is
 * gone immediately instead of living on in the trash. Returns true when the
 * note was deleted.
 */
export function DiscardIfEmpty(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2910772667, id);
}

/**
 * EmptyTrash permanently deletes every note in the trash.
 * 
 * FROZEN (pin-only form factor): same as RestoreNote — no trash UI exists.
 */
export function EmptyTrash(): $CancellablePromise<void> {
    return $Call.ByID(1373509360);
}

/**
 * GetNote returns a single note by id, including notes in the trash.
 */
export function GetNote(id: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(1276837971, id);
}

/**
 * TrashRetentionDays exposes the retention window to the frontend.
 * 
 * FROZEN (pin-only form factor): the purge countdown UI is gone; the constant
 * itself still drives the startup purge.
 */
export function GetTrashRetentionDays(): $CancellablePromise<number> {
    return $Call.ByID(144483264);
}

/**
 * ListNotes returns all live (non-deleted) notes, pinned notes first, most
 * recently updated within each group.
 */
export function ListNotes(): $CancellablePromise<$models.Note[] | null> {
    return $Call.ByID(27288930);
}

/**
 * ListTrash returns all notes currently in the trash, most recently deleted
 * first.
 */
export function ListTrash(): $CancellablePromise<$models.Note[] | null> {
    return $Call.ByID(2783601805);
}

/**
 * PurgeExpiredTrash permanently deletes notes that have been in the trash for
 * longer than TrashRetentionDays. It runs automatically at startup and
 * returns the number of purged notes.
 */
export function PurgeExpiredTrash(): $CancellablePromise<number> {
    return $Call.ByID(2438112529);
}

/**
 * RestoreNote moves a note out of the trash back into the live list.
 * 
 * FROZEN (pin-only form factor): the trash has no UI in this form factor;
 * kept for data compatibility. New code must not call it.
 */
export function RestoreNote(id: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(2189466573, id);
}

/**
 * SetApp wires the application handle after application.New so that the
 * service can broadcast change events to every window.
 */
export function SetApp(a: $models.appHandle | null): $CancellablePromise<void> {
    return $Call.ByID(3564796802, a);
}

/**
 * SetPinned pins or unpins a note.
 * 
 * FROZEN (pin-only form factor, ADR-0001): the pinned/unpinned distinction is
 * retired — every live note always has a window. Kept only so old clients and
 * existing data keep working; new code must not call it.
 */
export function SetPinned(id: string, pinned: boolean): $CancellablePromise<$models.Note> {
    return $Call.ByID(2234615425, id, pinned);
}

/**
 * TrashNote moves a note to the trash (recoverable for 60 days) and un-pins
 * it.
 */
export function TrashNote(id: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(931583385, id);
}

/**
 * UpdateNote replaces the content (and derived title) of a note. Notes in the
 * trash cannot be edited.
 */
export function UpdateNote(id: string, content: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(163960476, id, content);
}
