// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService manages the pin windows: one frameless always-on-top window
 * per live note. It is also the single source of truth for the theme, which
 * is persisted in the settings table and broadcast to every window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ClosePinnedWindow closes the pinned window for a note if it is open.
 * @param {string} noteID
 * @returns {$CancellablePromise<void>}
 */
export function ClosePinnedWindow(noteID) {
    return $Call.ByID(2822772649, noteID);
}

/**
 * GetTheme exposes the persisted theme so each window can apply it at
 * startup (the Go side is the single source of truth).
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(3411807052);
}

/**
 * OpenPinnedWindow opens a frameless, always-on-top desktop window showing
 * the given note. If the window already exists it is focused instead. Returns
 * true when a new window was created. Height is user-draggable (no content
 * auto-fit), minimum 150px.
 * @param {string} noteID
 * @returns {$CancellablePromise<boolean>}
 */
export function OpenPinnedWindow(noteID) {
    return $Call.ByID(1338467543, noteID);
}

/**
 * RequestFrontmostDelete asks the frontmost pin window to delete its note.
 * The frontend owns the flush-then-trash sequence (an in-flight edit must be
 * persisted before trashing), so this just forwards the request to that one
 * window. It is the menu-bar fallback for ⌘⌫.
 * @returns {$CancellablePromise<void>}
 */
export function RequestFrontmostDelete() {
    return $Call.ByID(507634945);
}

/**
 * SetTheme persists the theme, repaints the native backdrop of every open
 * window, and broadcasts theme:changed so all windows (and the antd
 * ConfigProvider) switch in the same frame.
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(mode) {
    return $Call.ByID(2230333288, mode);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Theme() {
    return $Call.ByID(1560765270);
}
