// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService creates and manages the note windows: the main list window
 * and one frameless always-on-top window per pinned note.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ClosePinnedWindow closes the pinned window for a note if it is open.
 */
export function ClosePinnedWindow(noteID: string): $CancellablePromise<void> {
    return $Call.ByID(2822772649, noteID);
}

/**
 * FocusMainWindow brings the main note list window to the front.
 */
export function FocusMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3976608946);
}

/**
 * OpenPinnedWindow opens a frameless, always-on-top desktop window showing
 * the given note. If the window already exists it is focused instead. Returns
 * true when a new window was created.
 */
export function OpenPinnedWindow(noteID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1338467543, noteID);
}

/**
 * SetTheme records the frontend theme and repaints the native backdrop of
 * every open window so the uncovered/under-construction window surface matches.
 * Called by the frontend at startup and whenever the theme toggles.
 */
export function SetTheme(mode: string): $CancellablePromise<void> {
    return $Call.ByID(2230333288, mode);
}

export function Theme(): $CancellablePromise<string> {
    return $Call.ByID(1560765270);
}
